spring:
  application:
    name: backend

  datasource:
    url: jdbc:postgresql://localhost:5432/mobile_app_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  session:
    store-type: none

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db/migration

  data:
    redis:
      host: localhost
      port: 6379
      password: redis123
      timeout: 3000ms

  mail:
    host: smtp.gmail.com
    port: 587
    username: hocnguyen1102.work@gmail.com
    password: cxwl urxj wfhc twnb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
        debug: false

management:
  health:
    redis:
      enabled: true

jwt:
  secret: 5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
  access-token-expiration: 900000        # 15 phút (ms)
  refresh-token-expiration: 604800000    # 7 ngày (ms)

otp:
  expiration: 300000     # 5 phút (ms)
  length: 6
  sender-name: "PTIT English App"

# Google OAuth2 — Web client (verify id_token aud); Android client khi token cấp cho app native
google:
  client-id: "35790031845-lg7v97e8m39912hadbctj60o1gv2qc3d.apps.googleusercontent.com"
  android-client-id: "35790031845-25t0jogk4g8hvpke5uj920gpvvjhv5ii.apps.googleusercontent.com"
